<a href="https://colab.research.google.com/github/ykenkou001/diveintocode-ml/blob/master/week4_session1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/My Drive/Colab Notebooks/week4_session1

/content/drive/My Drive/Colab Notebooks/week4_session1


In [0]:

import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import missingno as msno
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# week4 授業課題 信用情報の学習
# 【問題1】コンペティション内容の確認
### コンペティションのOverviewページ読み、「Home Credit Default Risk」について以下の観点について確認してください。  
### 何を学習し、何を予測するのか どのようなファイルを作りKaggleに提出するか 提出されたものはどういった指標値で評価されるのか

### 122個ある特徴量からその人が返済する確率を予測する
IDとTARGETがカラムとして入っているcsvファイルを提出する
TARGETにはその人が返済する確率が入っている


提出された課題はAUCで評価される

In [4]:
pwd

'/content/drive/My Drive/Colab Notebooks/week4_session1'

In [5]:
!unzip Data.zip -d week4_session1

Archive:  Data.zip
replace week4_session1/Data/application_test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [0]:
test_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/week4_session1/Data/application_test.csv")
train_df=pd.read_csv("/content/drive/My Drive/Colab Notebooks/week4_session1/Data/application_train.csv")

In [6]:
display(train_df.head())
display(test_df.head())

SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0

[5 rows x 122 columns]

SK_ID_CURR  ... AMT_REQ_CREDIT_BUREAU_YEAR
0      100001  ...                        0.0
1      100005  ...                        3.0
2      100013  ...                        4.0
3      100028  ...                        3.0
4      100038  ...                        NaN

[5 rows x 121 columns]

In [0]:
#欠損値がある列を削除
train_drop_df = train_df.dropna(axis=1)
test_drop_df = test_df.dropna(axis=1)

In [0]:
#objectタイプの列を削除する
object_columns = train_drop_df.select_dtypes(include=object).columns
train_drop_df = train_drop_df.drop(object_columns, axis=1)
test_drop_df = test_drop_df.drop(object_columns, axis=1)

In [0]:
X = train_drop_df.drop("TARGET", axis=1)
y = train_drop_df["TARGET"]

In [0]:
# X_testの列をXに合わせる
X_test = test_drop_df[X.columns]

In [0]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

In [12]:
forest = RandomForestClassifier(n_estimators=10)
forest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_val_pred = forest.predict(X_val)

In [14]:
def evaluate(y_test, y_pred):
    """
    2値分類の評価指標を計算する
    """
    acc = metrics.accuracy_score(y_test, y_pred)
    precision = metrics.precision_score(y_test, y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    confusion = metrics.confusion_matrix(y_test, y_pred)
    return acc, precision, recall, f1, confusion

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

acc : 0.9199771065844585
precision : 0.11392405063291139
recall : 0.0014775898867181087
f1 : 0.0029173419773095626
confusion matrix 
 [[70717    70]
 [ 6082     9]]


# 【問題3】テストデータに対する推定
テストデータ（application_test.csv）に対して推定を行い、Kaggleに提出を行ってください。

正しく提出が行えていれば、精度は低くても構いません。

In [0]:
y_pred = forest.predict(X_test)

# 4.特徴量エンジニアリング
ベースラインモデルを元に、入力する特徴量に様々な工夫を行い精度を向上させていきます。

# 【問題4】特徴量エンジニアリング¶
精度を上げるために以下のような観点で 特徴量エンジニアリング（Feature Engineering） を行ってください。  
・どの特徴量を使うか  
・どう前処理をするか  
何をした時に検証データに対する評価指標がどのようになったかをまとめてください。最低5パターンの学習・検証を行ってください。  

精度が高かったものに関してはテストデータに対しても推定を行い、Kaggleに提出を行ってください。  

## ・欠損値を０で埋める。

In [16]:
train_drop_df = train_df.fillna(0)
test_drop_df = test_df.fillna(0)

#objectタイプの列を削除する
object_columns = train_drop_df.select_dtypes(include=object).columns
train_drop_df = train_drop_df.drop(object_columns, axis=1)
test_drop_df = test_drop_df.drop(object_columns, axis=1)

X = train_drop_df.drop("TARGET", axis=1)
y = train_drop_df["TARGET"]

# X_testの列をXに合わせる
X_test = test_drop_df[X.columns]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

forest.fit(X_train, y_train)
y_val_pred = forest.predict(X_val)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

acc : 0.920224251411327
precision : 0.3793103448275862
recall : 0.01083565916926613
f1 : 0.02106943335993615
confusion matrix 
 [[70679   108]
 [ 6025    66]]


## ・欠損値を平均値で埋める。

In [0]:

train_drop_df = train_df.fillna(train_df.mean())
test_drop_df = test_df.fillna(test_df.mean())

#objectタイプの列を削除する
object_columns = train_drop_df.select_dtypes(include=object).columns
train_drop_df = train_drop_df.drop(object_columns, axis=1)
test_drop_df = test_drop_df.drop(object_columns, axis=1)

X = train_drop_df.drop("TARGET", axis=1)
y = train_drop_df["TARGET"]

# X_testの列をXに合わせる
X_test = test_drop_df[X.columns]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

forest.fit(X_train, y_train)
y_val_pred = forest.predict(X_val)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

## ・欠損値を中央値で埋める。

In [17]:
train_drop_df = train_df.fillna(train_df.median())
test_drop_df = test_df.fillna(test_df.median())

#objectタイプの列を削除する
object_columns = train_drop_df.select_dtypes(include=object).columns
train_drop_df = train_drop_df.drop(object_columns, axis=1)
test_drop_df = test_drop_df.drop(object_columns, axis=1)

X = train_drop_df.drop("TARGET", axis=1)
y = train_drop_df["TARGET"]

# X_testの列をXに合わせる
X_test = test_drop_df[X.columns]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

forest.fit(X_train, y_train)
y_val_pred = forest.predict(X_val)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

acc : 0.9194437940633211
precision : 0.27631578947368424
recall : 0.010343129207026762
f1 : 0.019939863902516224
confusion matrix 
 [[70622   165]
 [ 6028    63]]


## ・欠損値を最頻値で埋める。

In [0]:
train_drop_df = train_df.fillna(train_df.mode())
test_drop_df = test_df.fillna(test_df.mode())

#objectタイプの列を削除する
object_columns = train_drop_df.select_dtypes(include=object).columns
train_drop_df = train_drop_df.drop(object_columns, axis=1)
test_drop_df = test_drop_df.drop(object_columns, axis=1)

X = train_drop_df.drop("TARGET", axis=1)
y = train_drop_df["TARGET"]

# X_testの列をXに合わせる
X_test = test_drop_df[X.columns]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

forest.fit(X_train, y_train)
y_val_pred = forest.predict(X_val)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

## ・重要そうな特徴量を選んで残りは削除する。

In [19]:
#objectタイプの列を削除する
select_columns = ["AMT_INCOME_TOTAL", "AMT_CREDIT", "AMT_ANNUITY"]
train_drop_df = train_df[select_columns]
test_drop_df = test_df[select_columns]

train_drop_df = train_drop_df.dropna(axis=1)
test_drop_df = test_drop_df.dropna(axis=1)

X = train_drop_df
y = train_df["TARGET"]

# X_testの列をXに合わせる
X_test = test_drop_df
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=0)

forest.fit(X_train, y_train)
y_val_pred = forest.predict(X_val)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*evaluate(y_val, y_val_pred)))

acc : 0.9102994354691849
precision : 0.08116545265348596
recall : 0.012805779018223608
f1 : 0.022121384004537722
confusion matrix 
 [[69904   883]
 [ 6013    78]]
