# 配列の作成

## Numpyの読み込み

In [2]:
import numpy as np

sample_ndarray = np.array([1, 2, 3])
print(sample_ndarray)

sample_ndarray = np.array([[1, 2 ,3], [4, 5, 6]])
print(sample_ndarray)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [3]:
print(2 + [1, 2, 3])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [4]:
a = 2
b_list=[1, 2, 3]
c_list = []

for b in b_list:
    c_list.append(a + b)
print(c_list)

[3, 4, 5]


In [7]:
num = 2 + np.array([1, 2, 3])
print(num)
print(type(num))
print(type([1, 2, 3]))

[3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
print(np.array([1, 2, 3]) * np.array([1, 2, 3]))
print(np.array([1, 2, 3]) > np.array([2, 2, 2]))

[1 4 9]
[False False  True]


In [10]:
print(np.array([2]) + np.array([1, 2, 3]))
print(np.array([2, 2]) + np.array([1, 2, 3]))

[3 4 5]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [15]:
print(np.array([1, 2, 3]). ndim)
print(np.array([1, 2, 3]).shape)
print(np.array([1, 2, 3]).dtype)
print(type(np.array([1, 2, 3])))

1
(3,)
int32
<class 'numpy.ndarray'>


# 3.いろいろな配列作成方法

In [18]:
sample_ndarray = np.arange(50, 200, 2)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156
 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192
 194 196 198]
(75,)


In [19]:
sample_ndarray = np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
(100,)


In [20]:
sample_ndarray = 7*np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7.]
(100,)


In [21]:
sample_ndarray = np.zeros(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
(100,)


In [23]:
sample_ndarray = np.arange(10)
print(sample_ndarray)
print(sample_ndarray[3])


[0 1 2 3 4 5 6 7 8 9]
3
