# 配列の作成

## Numpyの読み込み

In [1]:
import numpy as np

sample_ndarray = np.array([1, 2, 3])
print(sample_ndarray)

sample_ndarray = np.array([[1, 2 ,3], [4, 5, 6]])
print(sample_ndarray)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [2]:
print(2 + [1, 2, 3])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [3]:
a = 2
b_list=[1, 2, 3]
c_list = []

for b in b_list:
    c_list.append(a + b)
print(c_list)

[3, 4, 5]


In [4]:
num = 2 + np.array([1, 2, 3])
print(num)
print(type(num))
print(type([1, 2, 3]))

[3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
print(np.array([1, 2, 3]) * np.array([1, 2, 3]))
print(np.array([1, 2, 3]) > np.array([2, 2, 2]))

[1 4 9]
[False False  True]


In [6]:
print(np.array([2]) + np.array([1, 2, 3]))
print(np.array([2, 2]) + np.array([1, 2, 3]))

[3 4 5]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [7]:
print(np.array([1, 2, 3]). ndim)
print(np.array([1, 2, 3]).shape)
print(np.array([1, 2, 3]).dtype)
print(type(np.array([1, 2, 3])))

1
(3,)
int32
<class 'numpy.ndarray'>


# 3.いろいろな配列作成方法

In [8]:
sample_ndarray = np.arange(50, 200, 2)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156
 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192
 194 196 198]
(75,)


In [9]:
sample_ndarray = np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
(100,)


In [27]:
sample_ndarray = 7*np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7.]
(100,)


In [28]:
sample_ndarray = np.zeros(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
(100,)


# Numpy入門2　基本的な配列処理

In [29]:
sample_ndarray = np.arange(10)
print(sample_ndarray)
print(sample_ndarray[3])
print(sample_ndarray[:3])
print(sample_ndarray[-1])
print(sample_ndarray[::2])
print(sample_ndarray[::-1])

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2]
9
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [30]:
a_ndarray = np.arange(4)
print(a_ndarray)
print(a_ndarray.shape)
b_ndarray = a_ndarray.reshape(2, 2)
print(b_ndarray)
print(b_ndarray.shape)

[0 1 2 3]
(4,)
[[0 1]
 [2 3]]
(2, 2)


# 多次元での要素の取り出し

In [31]:
sample_ndarray = np.arange(6).reshape(2, 3)
print(sample_ndarray)
print(sample_ndarray[1, 2])
print(sample_ndarray[:, 1:])

[[0 1 2]
 [3 4 5]]
5
[[1 2]
 [4 5]]


ndarrayには平均値や合計を求めるメソッドがあります。sumメソッドを使うと合計値、meanメソッドを使うと平均値が求められます。この時引数にaxis=0のように軸を指定すると、配列のある方向に対しての処理を行うことができます。.shapeを使い形が（2、3）であったとしたら、2つの要素がある軸が0番目の軸、3つの要素がある軸が1番目の軸です。sumメソッドやmeanメソッドで軸を指定すると、その軸が消えた形のndarrayが得られます。

In [39]:
a_ndarray = np.arange(6)
print(a_ndarray)
b_ndarray = a_ndarray.reshape(2, 3)
print(b_ndarray)
print("shape{}".format(b_ndarray.shape))
print("合計値は{}".format(b_ndarray.sum()))
print("0番目の軸方向の合計は{}".format(b_ndarray.sum(axis=0)))
print("1番目の軸方向の平均は{}".format(b_ndarray.mean(axis=0)))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
shape(2, 3)
合計値は15
0番目の軸方向の合計は[3 5 7]
1番目の軸方向の平均は[1.5 2.5 3.5]
