In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [2]:
print(np.dot(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題1】行列積を手計算する

#### [ [ (-1* 0)+(2* 0)+(3* 2), (-1* 2)+(2* 2)+(3* 9), (-1* 1)+(2* -8)+(3* -1) ],  
#### [ (4* 0)+(-5* 0)+(6* 2), (4* 2)+(-5* 2)+(6* 9), (4* 1)+(-5* -8)+(6* -1) ],  
#### [ (7* 0)+(8* 0)+(-9* 2), (7* 2)+(8* 2)+(-9* 9), (7* 1)+(8* -8)+(-9* -1) ] ]  
#### =[ [  6&nbsp;&emsp;29&emsp;  -20]  
#### &emsp;[ 12&emsp;52&emsp;  38]  
#### &emsp;[-18&nbsp;  -51&emsp;  -48]]

# 【問題2】NumPyの関数による計算


In [3]:
print(np.dot(a_ndarray, b_ndarray)) # np.dot()の場合

print(np.matmul(a_ndarray, b_ndarray)) # np.matmul()の場合

print(a_ndarray@ b_ndarray) # の場合

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題3】ある要素の計算を実装

In [4]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]]) # 行列A
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]]) # 行列B

line_column = a_ndarray[0,:]* b_ndarray[:, 0] # 行列Aの0行目と行列Bの０列目の積

print("行列Aの0行目と行列Bの0列目の積は: {}".format(sum(line_column)))

行列Aの0行目と行列Bの0列目の積は: 6


# 【問題4】行列積を行う関数の作成

In [11]:
# A[a, :]* B[:, j]を定義する関数

def line_column(a): #行列Aのa行目
    
    n = A.shape #行列Aのサイズ
    m = B.shape #行列Bのサイズ
    l = n[1] #行列Aの列数=行列Bの行数
    result_0 = np.array([]) # 行列Aのi行目と行列Bのj列目の積を格納

    for i in range(l):
        t = A[a, :]* B[:, i] # A[a, :]*B[:, i]を変数に格納
        w = np.sum(t) # tの総和
        result_0 = np.append(result_0, w) # wをresultに追加
    
    return result_0

A = a_ndarray
B = b_ndarray

print("A[0, :]*B[:, 0]は\n{}".format(line_column(0)))

A[0, :]*B[:, 0]は
[  6.  29. -20.]


In [14]:
# 行列AとBを引数に受け取り、行列積を返す関数を定義する。

def matrix_product(A, B):
    
    n = A.shape #行列Aのサイズ
    m = B.shape #行列Bのサイズ
    l = n[1] #行列Aの列（＝行列Bの行数）
    k = m[0] #行列Bの行数
    result = np.array([]) # 行列Aのi行目と行列Bのj列目の積を格納
    sum_result = np.array([]) # 各要素を格納する配列
    
    
    if l != k: #問題５の解答（if文によって条件分岐した）
        print("Aの列数とBの行数が等しくないので計算できない。")
        
    else:
        for j in range(l):
            nm = line_column(j) # 関数line_column()を変数に格納し、ループ処理する
            sum_result = np.append(sum_result, nm)

        last_result = sum_result.reshape([n[0], m[1]]) # l*kの配列に変換
    
    
        return last_result
A = a_ndarray
B = b_ndarray

print(matrix_product(A, B))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 【問題5】計算が定義されない入力を判定する

In [1]:
A = a_ndarray #行列A
B = b_ndarray #行列B
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

D = d_ndarray
E = e_ndarray
matrix_product(D, E)
print(matrix_product(A, B))

NameError: name 'a_ndarray' is not defined

# 【問題6】転置

In [ ]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

D = d_ndarray
E = e_ndarray

print(np.matmul(D, E))

In [ ]:
print(".Tバージョン: \n{}".format(np.matmul(D, E.T)))
print("np.transpose()バージョン: \n{}".format(np.matmul(D, np.transpose(E))))